server:
  port: 8080

# spring自己的异步任务线程池的大小
#task:
#  corePoolSize: 10
#  maxPoolSize: 50
#  queueCapacity: 200
#  threadNamePrefix: "WarehouseExecutor-"
# spring的配置，多环境的配置使用k8s的配置文件进行替换，不再使用本地配置文件的配置， 这里这个配置是ok的，但是为了服务能启动，数据库的使用先注释掉
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/ddd_example?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    username: root
#    password: QpJFDmB3LAww1RCy
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    # 计算密集型，非io密集型，先配置5
#    druid:
#      initial-size: 5
#      minIdle: 5
#      maxActive: 20
#      # 最大等待时间，内网：800，外网：1200, 配置4000（三次握手1s）
#      maxWait: 6000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 30000
#      validationQuery: SELECT 1
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: false
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
    # redis的启动也是ok的，服务能启动，先注释掉
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 10
#    password: v8oB9GrMiXjYp5fi
#    timeout: 5000 # 连接超时时间5000ms
#    lettuce:   # 这个是spring-data-redis自己的线程池lettuce的配置，redisson是需要自己配置线程池的
#      pool:
#        max-active: 8 # 连接池中最大连接数
#        max-wait: -1 # 获取连接的最大等待时间（毫秒），-1 表示无限等待
#        max-idle: 8 # 连接池中最大空闲连接数
#        min-idle: 5 # 连接池中最小空闲连接数

# 先不配置这些，需要调优的时候再弄
redisson:
  coreSize: 8         # 2倍cpu的数量
  connectSize: 32     # 连接数别太大，多机器一起链接会把redis的链接打满
  idleSize: 8
  timeout: 5000

# elastic的索引名和登录，能启动，先注释
#elasticsearch:
#  host: 127.0.0.1,127.0.0.1 # k8s上动态配置es，需要按照string类型处理，可以动态解析 host1,host2,
#  port: 9200
#  username: name
#  password: pwd
#  max-connect-num: 100
#  max-connect-num-per-route: 50

# 异步线程池的配置很重要
customer:
  corePoolSize: 8
  maximumPoolSize: 16
  keepAliveTime: 60000
  queueCapacity: 200

# 日志配置的名字配置，应为考虑并发所以使用异步日志Log4j2的方案替换logback
logging:
  config: classpath:log4j2.xml

# 监控点配置
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 所有的都监控
  endpoint:
    prometheus:
      enabled: true

# openAPI文档配置(springboot 3.5.0的版本配置这个有点问题)
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: false
  packages-to-scan: com.ddd.example.adapter.controller






