apiVersion: v1
kind: Service
metadata:
  name: com-ddd-example
  namespace: name-space
spec:
  selector:
    app: com-ddd-example
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8410
      targetPort: 8410
